### ISSUE TITLE
[comp:modal] Chrome < 87 时，modal, drawer 无法正常显示

### ISSUE THREAD

**Issue by danranVm** [IDuxFE/idux#1038]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
如果遇到该问题：请检查一下 .ix-modal-wrapper 的样式，是不是正确。

```css
.ix-modal-wrapper {
    z-index: 1000;
    overflow: auto;
    outline: none;
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
}
```

如果显示被压缩成为了 `inset: 0`, 在 Chrome < 87 版本时，无法正常显示。

解决方案：
- 修改打包工具的 css 压缩参数，以 vite 为例：参见 https://cn.vitejs.dev/config/build-options.html#build-csstarget
