### ISSUE TITLE
不使用组件库默认的 reset 样式，需要设置一些必须的全局样式

### ISSUE THREAD

**Issue by danranVm** [IDuxFE/idux#1194]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
```ts
// 如果不需要 reset 全局样式，移除下一行代码
// import "@idux/components/style/core/reset.default.min.css";
```

如果你移除或者注释掉了上面的 reset 代码，则需要设置一些必须的全局样式，否则会导致部分组件样式异常。

```css
// 这些样式是必须的。

*,
::before,
::after {
  background-repeat: no-repeat; /* Set `background-repeat: no-repeat` to all elements and pseudo elements */
  box-sizing: inherit;
}

::before,
::after {
  text-decoration: inherit; /* Inherit text-decoration and vertical align to ::before and ::after pseudo elements */
  vertical-align: inherit;
}

* {
  padding: 0; /* Reset `padding` and `margin` of all elements */
  margin: 0;
}

button,
input,
optgroup,
select,
textarea {
  font: inherit; /* Specify font inheritance of form elements */
}
```

如果你还遇到了没有 reset 而导致的其他样式问题，请在这个 issue 中告诉我们。
